### ISSUE TITLE
Supporting slider with no default value

### ISSUE THREAD

**Issue by amaatouq** [react-component/slider#378] opened 2017-12-12 21:53 UTC
I'm using the slider but would like to set the default value to null (i.e., having no tick selected--hidden handle). This is actually important for a variety of settings where anchoring bias should be avoided (i.e., designing an online experiment on charitable giving, guessing the correlation between two variables etc). 

Is this possible with rc-slider?

**Comment by yesmeck** [comment] 2018-03-07 08:51
Duplicate of #356

**Closed by yesmeck** 2018-03-07 08:51 UTC
