### ISSUE TITLE
Pushable feature inaccuracy

### ISSUE THREAD

**Issue by tasiek** [react-component/slider#199] opened 2017-01-04 11:18 UTC
There's an inaccuracy issue with pushable feature, when dragged through the "edge" of range.
After reaching the end, the final value is calculated incorrectly in some cases - it stops the handler too early.

![rc-slider-range-pushable-issue](https://cloud.githubusercontent.com/assets/4588259/21640718/5af4f6b4-d277-11e6-9184-67017cf97f39.gif)

In this case, pushable's range is set to 250.

**Comment by benjycui** [comment] 2017-01-25 09:06
It will be better if you can provide steps which can re-produce it every time.

**Comment by Robin-front** [comment] 2017-08-10 10:41
I think the reason is `mousemove` event is not continued.
![move](https://user-images.githubusercontent.com/6723674/29166576-8c1a26aa-7df9-11e7-9216-92748ef3e3ee.gif)

sometimes, the handle value will sudden skip to 1000 from 740.
But when pushing is impossible. the author reset the handle value to originalValue. That's why pushable feature inaccuracy. The logic [look here](https://github.com/react-component/slider/blob/master/src/Range.jsx#L222)

So, I think reset the handle value to limit is better, rather than originalValue.
`bounds[handle] = bounds[nextHandle] - (direction * threshold);`

**Comment by paranoidjk** [comment] 2017-09-15 02:47
@Robin-front Sounds reasonable，could you give a reproducible demo? or add some test case in your PR? Thanks.

**Comment by Robin-front** [comment] 2017-09-15 10:16
@paranoidjk okay, I will try. :)

**Comment by yesmeck** [comment] 2018-03-07 06:06
Fixed in 8.6.1

**Closed** 2018-03-07 06:06 UTC
Labels: bug, help wanted
