### ISSUE TITLE
 onAfterEnd - cant get event

### ISSUE THREAD

**Issue by AndreyMiloserdov** [react-component/slider#360] opened 2017-11-15 11:47 UTC
`  onEnd = () => {
    this.setState({ dragging: false });
    this.removeDocumentEvents();
    this.props.onAfterChange(this.getValue());
  }`
But correct
`onEnd = (evt) => {
    this.setState({ dragging: false });
    this.removeDocumentEvents();
    this.props.onAfterChange(this.getValue(), evt);
  }`

**Comment by yesmeck** [comment] 2018-03-07 08:52
Duplicate of #261

**Closed by yesmeck** 2018-03-07 08:52 UTC
