### ISSUE TITLE
Error w/ using `Slider` in function component (typescript)

### ISSUE THREAD

**Issue by jay-khatri** [react-component/slider#681] opened 2020-09-08 20:28 UTC
Hi there. I just started using this library in a function component in typescript, and I'm getting a weird error:

```
 Type '{ [x: string]: any; componentDidMount(): void; componentWillUnmount(): void; onMouseDown: (e: any) => void; onTouchStart: (e: any) => void; onFocus: (e: any) => void; onBlur: (e: any) => void; onMouseUp: () => void; ... 16 more ...; render(): Element; }' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more
```

Any suggestions?

**Comment by marco-fp** [comment] 2020-09-15 13:00
same issue

**Comment by eddydg** [comment] 2020-09-21 12:30
Hey, this issue is being discussed here https://github.com/react-component/slider/issues/656

**Comment by Kermit-Xuan** [comment] 2020-09-21 14:18
Duplicate of #656

**Closed by Kermit-Xuan** 2020-09-21 14:18 UTC
